FROM registry.access.redhat.com/ubi8/ubi-init
RUN yum update
RUN yum -y install httpd; yum clean all; systemctl enable httpd;
RUN echo "Successful Web Server Test - again, hi!" > /var/www/html/index.html
RUN yum install zip unzip -y
ADD preview-docs.zip ./
RUN unzip -o preview-docs.zip -d /var/www/html 
RUN mkdir /etc/systemd/system/httpd.service.d/; echo -e '[Service]\nRestart=always' > /etc/systemd/system/httpd.service.d/httpd.conf
EXPOSE 80
CMD [ "/sbin/init" ]